astar:
	g++ astar.cpp -g -std=c++11 -o as.bin
db2:
	g++ dual_bfs2.cpp -g -std=c++11 -o dbfs2.bin
dual_bfs:
	g++ dual_bfs.cpp -g -std=c++11 -o dbfs.bin
bfs:
	g++ bfs.cpp -g -std=c++11 -o bfs.bin
dk:
	g++ dijkstra.cpp -g -std=c++11 -o dk.bin
pcuiastar:
	g++ pcui_astar.cpp -g -std=c++11 -o pcuias.bin
pcuidb2:
	g++ pcui_dual_bfs2.cpp -g -std=c++11 -o pcuidbfs2.bin
pcuidualbfs:
	g++ pcui_dualbfs.cpp -g -std=c++11 -o pcuidbfs.bin
pcuibfs:
	g++ pcui_bfs.cpp -g -std=c++11 -o pcuibfs.bin
pcuidk:
	g++ pcui_dijkstra.cpp -g -std=c++11 -o pcuidk.bin
