all:
	g++ sizeofStruct.cpp -g -std=c++11 -o ss.bin

size:
	g++ sizeprint.cpp -g -std=c++11 -o sp.bin
scp:
	g++ strcpytest.cpp -g -std=c++11 -o scp.bin
missing:
	g++ missing_num.cpp -g -std=c++11 -o missing.bin
