rw2:
	g++ rw2.cpp -g -std=c++11 -o rw2.bin
all:
	g++ replace_word.cpp -g -std=c++11 -o rw.bin
pcui:
	g++ pcui_replace.cpp -g -std=c++11 -o pcui.bin
pcui2:
	g++ pcui_replace2.cpp -g -std=c++11 -o pcui2.bin
