
all:
	g++ git_version3.cpp -g -std=c++11 -o git_ver3
hehe2:
	g++ git_version2.cpp -g -std=c++11 -o git_ver2
hehe:
	g++ git_version.cpp -g -std=c++11 -o git_ver
pcui:
	g++ git_pcui.cpp -g -std=c++11 -o git_pcui
pcui2:
	g++ git_pcui2.cpp -g -std=c++11 -o git_pcui2
pcui3:
	g++ git_pcui3.cpp -g -std=c++11 -o git_pcui3
